services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: PostgreSQLDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: